template:

  - sensor:

      - name: Axpert PV To House Power
        unique_id: axpert_pv_to_house_power
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        availability: >
          {{ has_value('sensor.debarras_maison_puissance_pv')
             and has_value('sensor.axpert_battery_charge_power') }}
        state: >
          {% set pv = states('sensor.debarras_maison_puissance_pv')|float(0) %}
          {% set charge = states('sensor.axpert_battery_charge_power')|float(0) %}
          {{ [pv-charge,0]|max }}

      - name: Axpert PV To Battery Power
        unique_id: axpert_pv_to_battery_power
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        availability: >
          {{ has_value('sensor.axpert_battery_status')
             and has_value('sensor.debarras_maison_puissance_pv')
             and has_value('sensor.axpert_battery_charge_power') }}
        state: >
          {% if is_state('sensor.axpert_battery_status','En charge') %}
            {% set pv = states('sensor.debarras_maison_puissance_pv')|float(0) %}
            {% set charge = states('sensor.axpert_battery_charge_power')|float(0) %}
            {{ [pv,charge]|min }}
          {% else %}
            0
          {% endif %}

      - name: Axpert Battery To House Power
        unique_id: axpert_battery_to_house_power
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        availability: "{{ has_value('sensor.axpert_battery_discharge_power') }}"
        state: >
          {{ states('sensor.axpert_battery_discharge_power') }}

      - name: Axpert Grid To Battery Power
        unique_id: axpert_grid_to_battery_power
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        availability: >
          {{ has_value('sensor.axpert_battery_charge_power')
             and has_value('sensor.debarras_maison_puissance_pv') }}
        state: >
          {% if is_state('binary_sensor.debarras_maison_charge_sur_reseau','on') %}
            {% set charge = states('sensor.axpert_battery_charge_power')|float(0) %}
            {% set pv = states('sensor.debarras_maison_puissance_pv')|float(0) %}
            {{ [charge-pv,0]|max }}
          {% else %}
            0
          {% endif %}

      - name: Axpert Grid To House Power
        unique_id: axpert_grid_to_house_power
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        availability: >
          {{ has_value('sensor.debarras_maison_puissance_sortie')
             and has_value('sensor.axpert_pv_to_house_power')
             and has_value('sensor.axpert_battery_to_house_power') }}
        state: >
          {% if is_state('select.debarras_maison_axpert_output_mode','E2C') %}
            {% set load = states('sensor.debarras_maison_puissance_sortie')|float(0) %}
            {% set pv = states('sensor.axpert_pv_to_house_power')|float(0) %}
            {% set batt = states('sensor.axpert_battery_to_house_power')|float(0) %}
            {{ [load-pv-batt,0]|max }}
          {% else %}
            0
          {% endif %}

      - name: Axpert Grid Total Power
        unique_id: axpert_grid_total_power
        unit_of_measurement: W
        device_class: power
        state_class: measurement
        availability: >
          {{ has_value('sensor.axpert_grid_to_house_power')
             and has_value('sensor.axpert_grid_to_battery_power') }}
        state: >
          {{
            (
            states('sensor.axpert_grid_to_house_power')|float(0)
            +
            states('sensor.axpert_grid_to_battery_power')|float(0)
            )|round(0)
          }}

sensor:

  - platform: integration
    source: sensor.axpert_grid_to_house_power
    name: Axpert Grid To House Energy
    unique_id: axpert_grid_to_house_energy
    unit_prefix: k
    round: 3
    method: trapezoidal

  - platform: integration
    source: sensor.axpert_grid_to_battery_power
    name: Axpert Grid To Battery Energy
    unique_id: axpert_grid_to_battery_energy
    unit_prefix: k
    round: 3
    method: trapezoidal

  - platform: integration
    source: sensor.axpert_grid_total_power
    name: Axpert Grid Total Energy
    unique_id: axpert_grid_total_energy
    unit_prefix: k
    round: 3
    method: trapezoidal

  - platform: integration
    source: sensor.axpert_pv_to_house_power
    name: Axpert PV To House Energy
    unique_id: axpert_pv_to_house_energy
    unit_prefix: k
    round: 3
    method: trapezoidal

  - platform: integration
    source: sensor.axpert_pv_to_battery_power
    name: Axpert PV To Battery Energy
    unique_id: axpert_pv_to_battery_energy
    unit_prefix: k
    round: 3
    method: trapezoidal

  - platform: integration
    source: sensor.axpert_battery_to_house_power
    name: Axpert Battery To House Energy
    unique_id: axpert_battery_to_house_energy
    unit_prefix: k
    round: 3
    method: trapezoidal
